DevBlog/DevBlog/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevBlog.ViewModels.ImageViewModels;
using System.Globalization;
using DevBlog.DataAccess;
using DevBlog.Models;

namespace DevBlog.Controllers
{
    [Authorize(Roles = "Dev")]
    public class ImageController : Controller
    {
        ImageRepository repository = new ImageRepository();

        [HttpPost]
        public ActionResult Upload(ImageUploadViewModel model)
        {
            if (ModelState.IsValid) {
                string image = DateTime.UtcNow.ToString("yyMMddhhmmssffff", CultureInfo.InvariantCulture)
                    + System.IO.Path.GetFileName(model.ImageFile.FileName);
                model.Path = "~/Images/" + image;
                string path = System.IO.Path.Combine(Server.MapPath("~/Images"),image);
                model.ImageFile.SaveAs(path);

                repository.Save(model.CreatModel());

                return RedirectToAction("Details","Post",new { ID = model.PostID});
            }
            else { return RedirectToAction("Details", "Post", new { ID = model.PostID }); }
        }

        public ActionResult Delete(int id) {
            ImageModel image = repository.GetByID(id);
            if (image != null) {
                int postID = (int)image.PostID;
                if (System.IO.File.Exists(Server.MapPath(image.Path))) {
                    System.IO.File.Delete(Server.MapPath(image.Path));
                }
                else {
                    throw new System.Exception(Server.MapPath(image.Path));
                }
                repository.Delete(image);
                return RedirectToAction("Details", "Post", new { ID = postID });
            }
            else {
                return HttpNotFound();
            }
        }
    }
}

DevBlog/DevBlog/Views/Image/_Display.cshtml
@model DevBlog.ViewModels.ImageViewModels.ImageDisplayViewModel

<div class="gallery_product col-lg-10 col-md-10 col-sm-10 col-xs-10 filter hdpe">
        <img src="@Url.Content(Model.Path)" class="img-responsive" style="width:800px; height:auto">
        <p>
            @if (User.IsInRole("Dev")) { <b> @Html.ActionLink("Delete", "Delete","Image", new { id = Model.ID },null) </b>}
        </p>
</div>

DevBlog/DevBlog/Views/Image/_Upload.cshtml
@model DevBlog.ViewModels.ImageViewModels.ImageUploadViewModel

@using (Html.BeginForm("Upload", "Image", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.PostID, new { @Value = Model.PostID })
                <input type="file" name="ImageFile" style="width: 100%;" required /> 
                @Html.ValidationMessageFor(model => model.Path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}